# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FantasticNativeComponents' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for MyAwesomeProject
  pod 'JWPlayer-SDK', '~> 3.0'
  # Pods for FantasticNativeComponents

  target 'FantasticNativeComponents-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FantasticNativeComponentsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
